apiVersion: v1
appVersion: "3.0"
description: A Helm chart for Kubernetes
name: pointservice-chart
version: 0.1.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - pointservice-database
