apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: kafkaconnect
      protocol: TCP
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
  selector:
    {{- include "kafka-connect.selectorLabels" . | nindent 4 }}
