apiVersion: v1
kind: ConfigMap
metadata:
    name: pointservice-config
data:
    DatabaseConnectionString__Host: {{(include "postgresql.fullname" .)}}
    DatabaseConnectionString__Database: {{.Values.postgresql.postgresqlDatabase}}
    DatabaseConnectionString__Port: {{.Values.postgresql.service.port | quote}}  
    ASPNETCORE_ENVIRONMENT: Development
---
apiVersion: v1
kind: Secret
metadata:
    name: pointservice-config-secret
type: Opaque
data:
    DatabaseConnectionString__UserName: {{.Values.postgresql.postgresqlUsername | b64enc}}
    DatabaseConnectionString__Password: {{.Values.postgresql.postgresqlPassword | b64enc}}
    Audience__PublicKey: {{.Values.audience.publicKey | b64enc}}
    Audience__PrivateKey: {{.Values.audience.privateKey | b64enc}}
    Audience__Iss: {{.Values.audience.iss | b64enc}}
    Audience__Aud: {{.Values.audience.aud | b64enc}}

    