apiVersion: v1
kind: ConfigMap
metadata:
    name: pointservice-config
data:
    DatabaseConnectionString__Host: {{.Values.externalPostgresql.postgresqlHost}}
    DatabaseConnectionString__Database: {{.Values.externalPostgresql.postgresqlDatabase}}
    DatabaseConnectionString__Port: {{.Values.externalPostgresql.postgresqlPort | quote}}  
    ASPNETCORE_ENVIRONMENT: Development
---
apiVersion: v1
kind: Secret
metadata:
    name: pointservice-config-secret
type: Opaque
data:
    DatabaseConnectionString__UserName: {{.Values.externalPostgresql.postgresqlUsername | b64enc}}
    DatabaseConnectionString__Password: {{.Values.externalPostgresql.postgresqlPassword | b64enc}}
    