apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    metadata:
      name: migration
    spec:
        initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                    name: pointservice-config
                    key: DatabaseConnectionString__Host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                    name: pointservice-config
                    key: DatabaseConnectionString__Port
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT; 
              do echo waiting for database; sleep 2; done;
        containers:
        - name: migration
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: [ "dotnet", "PointService.DatabaseMigration.dll", "migration"]
          env:
          - name: DatabaseConnectionString__Host
            valueFrom:
              configMapKeyRef:
                  name: pointservice-config
                  key: DatabaseConnectionString__Host
          - name: DatabaseConnectionString__Database
            valueFrom:
              configMapKeyRef:
                  name: pointservice-config
                  key: DatabaseConnectionString__Database
          - name: DatabaseConnectionString__Port
            valueFrom:
              configMapKeyRef:
                  name: pointservice-config
                  key: DatabaseConnectionString__Port
          - name: DatabaseConnectionString__UserName
            valueFrom:
              secretKeyRef:
                  name: pointservice-config-secret
                  key: DatabaseConnectionString__UserName
          - name: DatabaseConnectionString__Password
            valueFrom:
              secretKeyRef:
                  name: pointservice-config-secret
                  key: DatabaseConnectionString__Password        
        restartPolicy: Never