apiVersion: v1
kind: Service
metadata:
  name: {{ include "pointservice-notifications-config.fullname" . }}
  labels:
{{ include "pointservice-notifications-config.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.value }}
      targetPort: {{ .Values.service.port.alias }}
      protocol: TCP
      name: {{ .Values.service.port.alias }}
  selector:
    {{- include "pointservice-notifications-config.selectorLabels" . | nindent 4 }}