{
 "title": "PointService dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"pointservice-chart.*\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{pod=~\"pointservice-chart.*\"}) by(pod))/1024/1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PointService Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (controller, action ,le))*1000",
     "legendFormat": "0.99-{{controller}}-{{action}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (controller, action, le))*1000",
     "legendFormat": "0.95-{{controller}}-{{action}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[1m])) by (controller,action,le))*1000",
     "legendFormat": "0.5-{{controller}}-{{action}}"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket[1m])) by (controller, action ,le))*1000",
     "legendFormat": "Max-{{controller}}-{{action}}"
    }
   ]
  },
  {
   "title": "PointService RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (rate(http_requests_received_total[1m])) ",
     "legendFormat": "{{controller}}-{{action}}"
    }
   ]
  },
  {
   "title": "PointService Error Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action, code) (increase(http_requests_received_total{code=~\"5.+\"}[10m]))"
    }
   ]
  },
  {
   "title": "Ingress RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Ngress Error Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)(increase(nginx_ingress_controller_request_duration_seconds_count{endpoint !=\"metrics\", status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Ingress Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))*1000"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))*1000"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))*1000"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le))*1000"
    }
   ]
  }
 ]
}