apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: pointservice-app
    context: D:\projects\PointServiceRepository\src\PointService.WebAPI
deploy:
  kubectl:
    manifests:
    - pointservice-config.yaml
    - deployment.yaml
    - service.yaml
