apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pointservice-apiGateway-chart.fullname" . }}
  labels:
{{ include "pointservice-apiGateway-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pointservice-apiGateway-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pointservice-apiGateway-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - name: {{ .Values.service.port.alias }}
            containerPort: 80
            protocol: TCP
        env:
        startupProbe:
            httpGet:
                path: /health
                port: {{ .Values.service.port.alias }}
            failureThreshold: 5
            periodSeconds: 10   
        readinessProbe:
            httpGet:
                port: {{ .Values.service.port.alias }}
                path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
        resources:
            limits:
                memory: "200Mi"
